# general
alias ll='ls -l'

# git
alias g='git'
alias ga='git add'
alias gap='git add -p'
alias gb='git branch'
alias gbd='git branch -D'
alias gbr='git branch -r'
alias gc='git commit'
alias gcm='git commit -m'
alias gco='git checkout'
alias gcob='git checkout -b'
alias gcom='gco master'
alias gd='git diff'
alias gds='git diff --staged'
alias gl='git log'
alias glo='git log --oneline'
alias gmm='git merge master --no-edit'
alias gp='git push'
alias gpull='git pull'
alias gr='git reset'
alias grh='git reset --hard'
alias gs='git status'
alias gum='gpull origin master'
alias gumm='gum && gmm'

