# general
alias ll='ls -l'
alias grep='grep --color'

# git
alias g='git'
alias ga='git add'
alias gap='git add -p'
alias gb='git branch'
alias gbd='git branch -D'
alias gbr='git branch -r'
alias gc='git commit'
alias gcl='git clone'
alias gcm='git commit -m'
alias gco='git checkout'
alias gcob='git checkout -b'
alias gcom='gco master'
alias gd='git diff'
alias gds='git diff --staged'
alias gfa='git fetch --all'
alias gl='git log'
alias glo='git log --oneline'
alias gmm='git merge master --no-edit'
alias gp='git push'
alias gpa='git fetch --all && git pull --all'
alias gpull='git pull'
alias gr='git reset'
alias grh='git reset --hard'
alias gs='git status'
alias gst='git stash'
alias gstc='git stash clear'
alias gstl='git stash list'
alias gsts='git stash show'
alias gum='gpull origin master'
alias gumm='gum && gmm'

